ENT.Base = "base_ai"
ENT.Type = "ai"
ENT.AutomaticFrameAdvance = true
ENT.PrintName = "LockSys"
ENT.Author = "GmodeProject.com [Ivitokun]"
ENT.Category = "GMPSys"
ENT.Instructions = "" 
ENT.Spawnable = true
ENT.AdminSpawnable = true