-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
--[[--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------]]
TEAM_CITIZEN = DarkRP.createJob("Гражданин", {
	color = Color(20, 150, 20, 255),
	model = "M",
	description = [[Вы - обычный гражданский, ваша задача:
	найти себе работу, обеспечить себя жильём и пищей. 
	Найти свою роль в обществе.]],
	weapons = {},
	command = "citizen",
	max = 0,
	salary = 175,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = false,
	category = "Граждыне",
	PlayerLoadout = function(ply)ply:SetModel(ply.Info.Model or "models/humans/modern/male_02_02.mdl") ply:SetSkin(ply.Info.Skin) end
})

TEAM_POLICE = DarkRP.createJob("Полицейский", {
	color = Color(25, 25, 170, 255),
	model = "M",
	description = [[Вы - служитель закона, ваша задача:
	защищать права мирных граждан,следить за порядком, 
	и достойно несите свою службу.]],
	weapons = {"arrest_stick", "unarrest_stick", "stunstick", "door_ram", "weaponchecker"},
	command = "cp",
	max = 15,
	salary = 220,
	admin = 0,
	vote = false,
	hasLicense = true,
	category = "Правоохранительные органы",
	customCheck = function(ply) return ply:GetNWBool("ment") end,
	CustomCheckFailMsg = "Вы не проходили тест!", 
	PlayerLoadout = function(ply)ply:SetModel(ply.Info.Model) ply:SetSkin(ply.Info.Skin) ply:SetPoliceLoyal()ply:Load() ply:updateJob(Rangs[ply:GetNWInt("rang")].name) end,
	PlayerDeath = function(ply)
		ply:teamBan()
        ply:changeTeam(GAMEMODE.DefaultTeam, true)
    end
})

TEAM_GUN = DarkRP.createJob("Продавец оружия", {
	color = Color(255, 140, 0, 255),
	model = "M",
	description = [[Вы - главный поставщик холодного
	и огнестрельного оружия в городе. Постройте свой
	магазин и развивайте свой бизнес, снабжая население оружием.
	Вам запрещено иметь при себе любой вид оружия, 
	вы занимаетесь исключительно его продажей.]],
	weapons = {},
	command = "gundealer",
	max = 5,
	salary = 175,
	admin = 0,
	vote = false,
	hasLicense = false,
	category = "Граждыне",
	PlayerLoadout = function(ply)ply:SetModel(ply.Info.Model) ply:SetSkin(ply.Info.Skin) end,
	PlayerDeath = function(ply)
		ply:teamBan()
        ply:changeTeam(GAMEMODE.DefaultTeam, true)
    end
})

TEAM_MEDIC = DarkRP.createJob("Доктор", {
	color = Color(47, 79, 79, 255),
	model = "M",
	description = [[Вы - доктор, вы спасаете жизни людей, и только вам 
	решать сколько она стоит. Вам запрещено иметь при себе любой вид оружия.]],
	weapons = {"med_kit"},
	command = "medic",
	max = 5,
	salary = 175,
	admin = 0,
	vote = false,
	hasLicense = false,
	medic = true,
	category = "Граждыне",
	PlayerLoadout = function(ply)ply:SetModel(ply.Info.Model) ply:SetSkin(ply.Info.Skin) end,
	PlayerDeath = function(ply)
		ply:teamBan()
        ply:changeTeam(GAMEMODE.DefaultTeam, true)
    end
})

TEAM_MAYOR = DarkRP.createJob("Мэр", {
	color = Color(150, 20, 20, 255),
	model = "M",
	description = [[Вы - мэр, глава этого города и авторитет среди его 
	жителей. Вам подчиняются все силы правопорядка включая Шефа полиции.
	Руководите правоохранительными органами, продавайте
	лицензии на оружие, занимайтесь организационными вопросами
	и участвуйте в жизни вашего города.
	Вам запрещено иметь при себе любой вид оружия.]],
	weapons = {},
	command = "mayor",
	max = 1,
	salary = 400,
	admin = 0,
	vote = false,
	hasLicense = false,
	mayor = true,
	category = "Правоохранительные органы",
	customCheck = function(ply) return ply:GetNWBool("canmar")  end,
	CustomCheckFailMsg = "Вы не баллотировались!", 
	PlayerLoadout = function(ply)ply:SetModel(ply.Info.Model) ply:SetSkin(ply.Info.Skin) end,
    PlayerDeath = function(ply, weapon, killer)
                ply:teamBan()
                ply:changeTeam(GAMEMODE.DefaultTeam, true)
		ply:SetNWBool("canmar", false)
                if killer:IsPlayer() then
                        DarkRP.notifyAll(0, 4, "Мэр, был убит.")
                else
                        DarkRP.notifyAll(0, 4, "Мэр, умер.")
                end
    end
})

TEAM_COOK = DarkRP.createJob("Повар", {
	color = Color(238, 99, 99, 255),
	model = "M",
	description = [[Вы являетесь повором, откройте кафе или ресторан, по 
	вашему выбору, торгуйте едой за деньги, люди в этом городе не должны 
	умирать от голода, иначе вы будете уволены с профессии. ]],
	weapons = {},
	command = "cook",
	max = 4,
	salary = 175,
	admin = 0,
	vote = false,
	hasLicense = false,
	cook = true,
	category = "Граждыне",
	PlayerLoadout = function(ply)ply:SetModel(ply.Info.Model) ply:SetSkin(ply.Info.Skin) end,
	PlayerDeath = function(ply)
		ply:teamBan()
        ply:changeTeam(GAMEMODE.DefaultTeam, true)
    end
})

TEAM_DRES = DarkRP.createJob("Торговец одеждой", {
	color = Color(47, 79, 79, 255),
	model = "M",
	description = [[Вы - Торговец одеждой, одевайте граждан города.]],
	weapons = {},
	command = "dress",
	max = 2,
	salary = 175,
	admin = 0,
	vote = false,
	hasLicense = false,
	category = "Граждыне"
})

-- Compatibility for when default teams are disabled
TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_COOK    = TEAM_COOK     or -1

-- Initial team when first spawning
GAMEMODE.DefaultTeam = TEAM_CITIZEN

-- Teams that belong to Civil Protection
GAMEMODE.CivilProtection = {
    [TEAM_POLICE] = true,
    [TEAM_MAYOR] = true,
}

-- Default categories
DarkRP.createCategory{
    name = "Граждыне",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 100,
}

DarkRP.createCategory{
    name = "Правоохранительные органы",
    categorises = "jobs",
    startExpanded = true,
    color = Color(25, 25, 170, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 101,
}